[package]
name = "matrix-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
deadpool-postgres = "0.14.0"
reqwest = "0.12.5"
tap = "1.0.1"
tokio = "1.38.1"
tokio-postgres = "0.7.10"
serde_json = "1.0.120"
log = "0.4.22"
